version: "3"
services:
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        stdin_open: true
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "8080:80"
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
    ai:
        build:
            dockerfile: Dockerfile
            context: ./ai
        volumes:
            - ./ai:/app