/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:c684aa0d-f364-40f6-b991-8bd5b065fee8",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_brwr9Qyvh",
    "aws_user_pools_web_client_id": "6jijj8cq874dftv19eilk0bq4i",
    "oauth": {}
};


export default awsmobile;
