spring:
  profiles:
    includes:
      - aws
      - credentials
  data:
    mongodb:
      host: onegodev.ddns.net
      port: 2727
      authentication-database: admin
      database: onego
      username: onego
      password: test123
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_brwr9Qyvh
