spring:
  data:
    mongodb:
      host: onegomongo.ddns.net
      port: 80
      authentication-database: admin
      database: onego
      username: onego
      password: test123
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_brwr9Qyvh
